title: Drew Sommer
email: drew@sommerengineering.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sommerengineering.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: no_twitter
github_username: apsommer
linkedin_username: apsommer # maybe?

# build settings
theme: minima
# theme: jekyll-theme-clean-blog

# layouts
defaults:
 -
   scope:
     path: "posts" # empty string means all files
   values:
     layout: "post"
     author: "John Doe"