title: Sommer Engineering
email: drew@sommerengineering.com
description: >-
  My latest product BarAudio provides audible realtime alerts for the financial markets. My recent project with Electrify America is a green initiative that simplifies the charging of electric vehicles. I love collaborating on teams and have experience mentoring others.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sommerengineering.com" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: apsommer
github_username: apsommer

# build settings
theme: minima
# theme: jekyll-theme-clean-blog

# layouts
defaults:
 -
   scope:
     path: "posts" # empty string means all files
   values:
     layout: "post"
     author: "John Doe"